namespace SpriteKind {
    export const bomb = SpriteKind.create()
    export const life = SpriteKind.create()
    export const BOSS = SpriteKind.create()
    export const darkbeetlebomber = SpriteKind.create()
    export const enemy2 = SpriteKind.create()
    export const projectile2 = SpriteKind.create()
}
namespace StatusBarKind {
    export const Ammo = StatusBarKind.create()
}
sprites.onOverlap(SpriteKind.life, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite)
    info.changeLifeBy(1)
    music.play(music.melodyPlayable(music.magicWand), music.PlaybackMode.UntilDone)
})
sprites.onOverlap(SpriteKind.bomb, SpriteKind.enemy2, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.spray, 500)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.UntilDone)
    info.changeScoreBy(1)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    enemy_pew = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . 2 . . . . . . . . . . . . 2 . 
        . 2 . . . . . . . . . . . . 2 . 
        . 2 . . . . . . . . . . . . 2 . 
        . 2 . 2 . . . . . . . . 2 . 2 . 
        . . . 2 . . . . . . . . 2 . . . 
        . . . 2 . . . . . . . . 2 . . . 
        . . . 2 . . . . . . . . 2 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SPACESHIP_SPACESHIP_SPACESHIP, 0, -200)
    enemy_pew.setKind(SpriteKind.bomb)
    music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.UntilDone)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.rings, 500)
    info.changeLifeBy(-1)
    music.play(music.melodyPlayable(music.buzzer), music.PlaybackMode.UntilDone)
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    sprites.destroy(Darkstar_Kingship, effects.fire, 10000)
    sprites.destroy(Darkstar_Kingship, effects.ashes, 10000)
    music.play(music.melodyPlayable(music.bigCrash), music.PlaybackMode.UntilDone)
    pause(11000)
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.bomb, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.disintegrate, 500)
    sprites.destroy(sprite, effects.spray, 500)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.UntilDone)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.rings, 500)
    info.changeLifeBy(-1)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.UntilDone)
})
sprites.onOverlap(SpriteKind.enemy2, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.rings, 500)
    info.changeLifeBy(-1)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.UntilDone)
})
info.onScore(500, function () {
    Darkstar_Kingship = sprites.create(img`
        .....................................1....666666666666666....1.....................................
        ......................666666666666666f66666666666622666666666f666666666666666......................
        .................6666666666666666666f6666666666666222666666666f6666666666666666666.................
        ............666666666666666666666666f6699999666666622269999966f666666666666666666666666............
        ...........6666666666666666666666666f6699999996666662999999966f6666666666666666666666666...........
        ..........66666666666666666666666666f6699999999999999999999966f66666666666666666666666666..........
        .........666666666666666666666666666f6699999999999999999999966f666666666666666666666666666.........
        ........666666666666666666666666666f666999999999999999999999666f666666666666666666666666666........
        .......6666666666666666666666666666f666669999999999999999966666f6666666666666666666666666666.......
        ......66666666666666666666666666666f666669999999999999992266666f66666666666666666666666666666......
        ......66666666666666666666666666666f666666699999999999992226666f66666666666666666666666666666......
        ......66666666666666666666666666666f666666666666666666666222666f66666666666666666666666666666......
        ......66666666666666666666666666666f666666666666666666666622266f66666666666666666666666666666......
        ......66666666666666666666666666666f666666666fffffffff666662226f66666666666666666666666666666......
        ......66666666666666666666666666666f66666666f666666666f66666226f66666666666666666666666666666......
        ......66666666666666666666666666666f6666666f66f66666f66f6666666f66666666666666666666666666666......
        ......6666666666666666666666666....16666666f6fff666fff6f66666661....6666666666666666666666666......
        ......666666666666666666666666......6666666f6fff666fff6f6666666......666666666666666666666666......
        ......66666666666666666666666.......6666666f6fff666fff6f6666666.......66666666666666666666666......
        ......6666666666666666666666........6666666f66f66666f66f6666666........6666666666666666666666......
        ......666666666666666666666.........66666666f666666666f66666666.........666666666666666666666......
        ......66666666666666666666...........66666666fffffffff66666666...........66666666666666666666......
        ......66666666666666666666...........6666666666666666666666666...........66666666666666666666......
        ......66666666666666666666...........6666666666666666666666666...........66666666666666666666......
        ......66666666666666666666...........6666666666666666666666666...........66666666666666666666......
        ......66666666666666666666...........6666666666666666666666666...........66666666666666666666......
        ......66666666666666666666..........1fffff666666666666666fffff1..........66666666666666666666......
        ......66666666666666666666.........1fff666fffffffffffffff666fff1.........66666666666666666666......
        ......666666666666666666666........6666f66661f6666666f16666f6666........666666666666666666666......
        ......6666666666666666666666......6ffff6f661ff6666666ff166f6ffff6......6666666666666666666666......
        ......66666666666666666666666....6fffff6f6.1f6fffffff6f1.6f6fffff6....66666666666666666666666......
        ......666666666666666666666666...6fffff6f1.1ff6666666ff1.1f6fffff6...666666666666666666666666......
        ......6666666666666666666666666..6fffff61..1f6f6fffff6f1..16fffff6..6666666666666666666666666......
        ......66666666666666666666666666.6ffff6....1f6f6fffff6f1....6ffff6.66666666666666666666666666......
        ......666666666666666666666666666.6666.....1f6f6fffff6f1.....6666.666666666666666666666666666......
        ......6666666666666666666666666666........11f6f66666f6f1.........6666666666666666666666666666......
        .......66666666666666666666666666666666666f1f6fffff6f6f1f66666666666666666666666666666666666.......
        ........66666666666666666666666666666666666ff6fffff6f6ff66666666666666666666666666666666666........
        .........66666666666666666691111111111119666f6fffff6f6f66691111111111116966666666666666666.........
        ..........66666666666666666166616666666616666f6666666f66661666666661666166666666666666666..........
        ...........66666666666666661666696666666166661.......16666166666669666616666666666666666...........
        ............666666666666666166666166666616666.........666616666661666661666666666666666............
        .............66666666666666166666696666616666.........66661666669666666166666666666666.............
        ..............6666666666666161666661666616666.........6666166661666661616666666666666..............
        ...............666666666666166166666966616666.........666616669666661661666666666666...............
        ................66666666666166666666616616666.........66661661666666666166666666666................
        .................6666666666166661666669616666.........6666169666661666616666666666.................
        ..................66666666616666616666611666...........66611666661666661666666666..................
        ...................666666669111111111111966.............669111111111111966666666...................
        ....................6666666666666666666666...............6666666666666666666666....................
        .....................66666666666666666666.................66666666666666666666.....................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        ...................................................................................................
        `, SpriteKind.BOSS)
    Darkstar_Kingship.setPosition(6, 12)
    Darkstar_Kingship.vx += 30
    Darkstar_Kingship.setBounceOnWall(true)
    statusbar = statusbars.create(20, 4, StatusBarKind.Health)
    statusbar.attachToSprite(Darkstar_Kingship, 25, 0)
    statusbar.value = 200
    while (statusbar.value > 0) {
        banzai_bill = sprites.createProjectileFromSprite(img`
            .....2.2.2.2.2.2.....
            ....2525252525252....
            ..12555555555555521..
            .1fffffffffffffffff1.
            .1fffffffffffffffff1.
            ..1fffffffffffffff1..
            ..1f1fffffffffff1f1..
            ..1f11fffffffff11f1..
            ..1f111fffffff111f1..
            ..1f1111fffff1111f1..
            ..1ff11f1fff1f11ff1..
            ..1fff1f1fff1f1fff1..
            ..1f1fffffffffff1f1..
            ..1f11fffffffff11f1..
            ..1f1211121112121f1..
            ..1f2121212121212f1..
            ..1ff12121212121ff1..
            ...1ff121112111ff1...
            ....1fffffffffff1....
            .....11111111111.....
            `, Darkstar_Kingship, 0, 30)
        banzai_bill.setKind(SpriteKind.projectile2)
        bullet_bill_1 = sprites.createProjectileFromSprite(img`
            . . . . 5 . 5 . 5 . 5 . 5 . . . . 
            . . . . 5 5 2 5 2 5 2 5 5 . . . . 
            . . . 1 5 2 2 2 2 2 2 2 5 1 . . . 
            . . 1 f f f f f f f f f f f 1 . . 
            . . 1 f f f f f f f f f f f 1 . . 
            . . 1 f f f f f f f f f f f 1 . . 
            . . 1 1 f f f f f f f f f 1 1 . . 
            . 1 1 1 f f f f f f f f f 1 1 1 . 
            1 1 1 1 f 1 f f f f f 1 f 1 1 1 1 
            1 1 . 1 f 1 f f f f f 1 f 1 . 1 1 
            1 1 . 1 f 1 1 f f f 1 1 f 1 . 1 1 
            1 1 . 1 f 1 2 1 f 1 2 1 f 1 . 1 1 
            . . . 1 f f 2 1 f 1 2 f f 1 . . . 
            . . . 1 f f f f f f f f f 1 . . . 
            . . . . 1 f f f f f f f 1 . . . . 
            . . . . . 1 1 1 1 1 1 1 . . . . . 
            `, Darkstar_Kingship, 30, 90)
        bullet_bill_1.setKind(SpriteKind.projectile2)
        bullet_bill_2 = sprites.createProjectileFromSprite(img`
            . . . . 5 . 5 . 5 . 5 . 5 . . . . 
            . . . . 5 5 2 5 2 5 2 5 5 . . . . 
            . . . . 5 2 2 2 2 2 2 2 5 1 . . . 
            . . 1 f f f f f f f f f f f 1 . . 
            . . 1 f f f f f f f f f f f 1 . . 
            . . 1 f f f f f f f f f f f 1 . . 
            . . 1 1 f f f f f f f f f 1 1 . . 
            . 1 1 1 f f f f f f f f f 1 1 1 . 
            1 1 1 1 f 1 f f f f f 1 f 1 1 1 1 
            1 1 . 1 f 1 f f f f f 1 f 1 . 1 1 
            1 1 . 1 f 1 1 f f f 1 1 f 1 . 1 1 
            1 1 . 1 f 1 2 1 f 1 2 1 f 1 . 1 1 
            . . . 1 f f 2 1 f 1 2 f f 1 . . . 
            . . . 1 f f f f f f f f f 1 . . . 
            . . . . 1 f f f f f f f 1 . . . . 
            . . . . . 1 1 1 1 1 1 1 . . . . . 
            `, Darkstar_Kingship, -30, 90)
        bullet_bill_2.setKind(SpriteKind.projectile2)
        pause(2000)
        tie_fighter_during_boss = sprites.createProjectileFromSprite(img`
            ...1............1...
            ..1f1..........1f1..
            .1ff1..........1ff1.
            1fff1..111111..1fff1
            1fff1.1ffffff1.1fff1
            1ff111ff9999ff111ff1
            1ffffff9ffff9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9ffff9ffffff1
            1ff111ff9999ff111ff1
            1fff1.1ffffff1.1fff1
            1fff1.1f1111f1.1fff1
            .1ff1..2....2..1ff1.
            ..1f1..........1f1..
            ...1............1...
            ....................
            ....................
            ....................
            ....................
            `, Darkstar_Kingship, 0, 45)
        tie_fighter_during_boss.x = randint(10, 150)
        tie_fighter_during_boss.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
        tie_fighter_during_boss.setKind(SpriteKind.enemy2)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 200)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 240)
        projectile2.setKind(SpriteKind.projectile2)
        tie_fighter_during_boss = sprites.createProjectileFromSprite(img`
            ...1............1...
            ..1f1..........1f1..
            .1ff1..........1ff1.
            1fff1..111111..1fff1
            1fff1.1ffffff1.1fff1
            1ff111ff9999ff111ff1
            1ffffff9ffff9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9ffff9ffffff1
            1ff111ff9999ff111ff1
            1fff1.1ffffff1.1fff1
            1fff1.1f1111f1.1fff1
            .1ff1..2....2..1ff1.
            ..1f1..........1f1..
            ...1............1...
            ....................
            ....................
            ....................
            ....................
            `, Darkstar_Kingship, 0, 45)
        tie_fighter_during_boss.x = randint(10, 150)
        tie_fighter_during_boss.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
        tie_fighter_during_boss.setKind(SpriteKind.enemy2)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 200)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 240)
        projectile2.setKind(SpriteKind.projectile2)
        tie_fighter_during_boss = sprites.createProjectileFromSprite(img`
            ...1............1...
            ..1f1..........1f1..
            .1ff1..........1ff1.
            1fff1..111111..1fff1
            1fff1.1ffffff1.1fff1
            1ff111ff9999ff111ff1
            1ffffff9ffff9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9ffff9ffffff1
            1ff111ff9999ff111ff1
            1fff1.1ffffff1.1fff1
            1fff1.1f1111f1.1fff1
            .1ff1..2....2..1ff1.
            ..1f1..........1f1..
            ...1............1...
            ....................
            ....................
            ....................
            ....................
            `, Darkstar_Kingship, 0, 45)
        tie_fighter_during_boss.x = randint(10, 150)
        tie_fighter_during_boss.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
        tie_fighter_during_boss.setKind(SpriteKind.enemy2)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 200)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 240)
        projectile2.setKind(SpriteKind.projectile2)
        tie_fighter_during_boss = sprites.createProjectileFromSprite(img`
            ...1............1...
            ..1f1..........1f1..
            .1ff1..........1ff1.
            1fff1..111111..1fff1
            1fff1.1ffffff1.1fff1
            1ff111ff9999ff111ff1
            1ffffff9ffff9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9f99f9ffffff1
            1ffffff9ffff9ffffff1
            1ff111ff9999ff111ff1
            1fff1.1ffffff1.1fff1
            1fff1.1f1111f1.1fff1
            .1ff1..2....2..1ff1.
            ..1f1..........1f1..
            ...1............1...
            ....................
            ....................
            ....................
            ....................
            `, Darkstar_Kingship, 0, 45)
        tie_fighter_during_boss.x = randint(10, 150)
        tie_fighter_during_boss.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
        tie_fighter_during_boss.setKind(SpriteKind.enemy2)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 200)
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . 7 . . . . 7 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, tie_fighter_during_boss, 0, 240)
        projectile2.setKind(SpriteKind.projectile2)
    }
})
sprites.onOverlap(SpriteKind.projectile2, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.rings, 500)
    info.changeLifeBy(-1)
    music.play(music.melodyPlayable(music.buzzer), music.PlaybackMode.UntilDone)
})
sprites.onOverlap(SpriteKind.bomb, SpriteKind.BOSS, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.spray, 500)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.UntilDone)
    info.changeScoreBy(1)
    statusbar.value += -1
})
sprites.onOverlap(SpriteKind.BOSS, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.rings, 500)
    info.changeLifeBy(-1)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.UntilDone)
})
let dark_beetle_bomber: Sprite = null
let xwing_dark_fighter: Sprite = null
let flying_bombomb: Sprite = null
let bullet_bill: Sprite = null
let PIGFO_RIDER: Sprite = null
let projectile: Sprite = null
let tie_fighter: Sprite = null
let projectile2: Sprite = null
let tie_fighter_during_boss: Sprite = null
let bullet_bill_2: Sprite = null
let bullet_bill_1: Sprite = null
let banzai_bill: Sprite = null
let statusbar: StatusBarSprite = null
let Darkstar_Kingship: Sprite = null
let enemy_pew: Sprite = null
let SPACESHIP_SPACESHIP_SPACESHIP: Sprite = null
effects.starField.startScreenEffect()
game.splash("GALAXY COMBAT 2")
game.splash("get 500 points to beat the boss")
game.splash("oh yeah by the way")
game.splash("good luck without dying")
game.splash("  continue hit A to begin :)")
SPACESHIP_SPACESHIP_SPACESHIP = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . 2 2 . . . . . . . 
    . 5 . . . . 2 2 2 2 . . . . 5 . 
    . 5 . . . . 2 2 2 2 . . . . 5 . 
    . 2 . . . . d 1 1 d . . . . 2 . 
    1 2 . 5 . . d 9 9 d . . 5 . 2 1 
    8 1 . 5 . . 8 d d 8 . . 5 . 1 8 
    8 8 1 2 . . 1 f f 1 . . 2 1 8 8 
    8 8 8 2 . . 1 1 1 1 . . 2 8 8 8 
    1 8 8 8 1 . 1 f f 1 . 1 8 8 8 1 
    . 1 8 8 8 1 1 8 8 1 1 8 8 8 1 . 
    . 4 1 8 8 8 1 8 8 1 8 8 8 1 4 . 
    . 4 4 1 8 8 1 1 1 1 8 8 1 4 4 . 
    . 4 4 4 1 1 5 2 2 5 1 1 4 4 4 . 
    . 5 2 5 . 1 5 2 2 5 1 . 5 2 5 . 
    . . 5 . . . . 5 5 . . . . 5 . . 
    `, SpriteKind.Player)
controller.moveSprite(SPACESHIP_SPACESHIP_SPACESHIP, 150, 150)
SPACESHIP_SPACESHIP_SPACESHIP.setFlag(SpriteFlag.StayInScreen, true)
info.setLife(175)
info.setScore(0)
game.onUpdateInterval(5000, function () {
    tie_fighter = sprites.createProjectileFromSide(img`
        ...1............1...
        ..1f1..........1f1..
        .1ff1..........1ff1.
        1fff1..111111..1fff1
        1fff1.1ffffff1.1fff1
        1ff111ff9999ff111ff1
        1ffffff9ffff9ffffff1
        1ffffff9f99f9ffffff1
        1ffffff9f99f9ffffff1
        1ffffff9ffff9ffffff1
        1ff111ff9999ff111ff1
        1fff1.1ffffff1.1fff1
        1fff1.1f1111f1.1fff1
        .1ff1..2....2..1ff1.
        ..1f1..........1f1..
        ...1............1...
        ....................
        ....................
        ....................
        ....................
        `, 0, 45)
    tie_fighter.x = randint(10, 150)
    tie_fighter.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
    tie_fighter.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 200)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 220)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 240)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 260)
})
game.onUpdateInterval(5000, function () {
    tie_fighter = sprites.createProjectileFromSide(img`
        ...1............1...
        ..1f1..........1f1..
        .1ff1..........1ff1.
        1fff1..111111..1fff1
        1fff1.1ffffff1.1fff1
        1ff111ff9999ff111ff1
        1ffffff9ffff9ffffff1
        1ffffff9f99f9ffffff1
        1ffffff9f99f9ffffff1
        1ffffff9ffff9ffffff1
        1ff111ff9999ff111ff1
        1fff1.1ffffff1.1fff1
        1fff1.1f1111f1.1fff1
        .1ff1..2....2..1ff1.
        ..1f1..........1f1..
        ...1............1...
        ....................
        ....................
        ....................
        ....................
        `, 0, 45)
    tie_fighter.x = randint(10, 150)
    tie_fighter.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
    tie_fighter.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 200)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 220)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 240)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 260)
})
game.onUpdateInterval(5000, function () {
    tie_fighter = sprites.createProjectileFromSide(img`
        ...1............1...
        ..1f1..........1f1..
        .1ff1..........1ff1.
        1fff1..111111..1fff1
        1fff1.1ffffff1.1fff1
        1ff111ff9999ff111ff1
        1ffffff9ffff9ffffff1
        1ffffff9f99f9ffffff1
        1ffffff9f99f9ffffff1
        1ffffff9ffff9ffffff1
        1ff111ff9999ff111ff1
        1fff1.1ffffff1.1fff1
        1fff1.1f1111f1.1fff1
        .1ff1..2....2..1ff1.
        ..1f1..........1f1..
        ...1............1...
        ....................
        ....................
        ....................
        ....................
        `, 0, 45)
    tie_fighter.x = randint(10, 150)
    tie_fighter.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
    tie_fighter.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 200)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 220)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 240)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . 7 . . . . 7 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, tie_fighter, 0, 260)
})
game.onUpdateInterval(9000, function () {
    PIGFO_RIDER = sprites.createProjectileFromSide(assets.image`P-FO RIDER`, 0, 70)
    PIGFO_RIDER.x = randint(10, 150)
    PIGFO_RIDER.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    PIGFO_RIDER.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 100)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 120)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 140)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 180)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 200)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 220)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 240)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 260)
})
game.onUpdateInterval(9000, function () {
    PIGFO_RIDER = sprites.createProjectileFromSide(assets.image`P-FO RIDER`, 0, 70)
    PIGFO_RIDER.x = randint(10, 150)
    PIGFO_RIDER.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    PIGFO_RIDER.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 100)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 120)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 140)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 180)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 200)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 220)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 240)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 260)
})
game.onUpdateInterval(0.1, function () {
    if (info.score() >= 500) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    }
})
game.onUpdateInterval(2500, function () {
    bullet_bill = sprites.createProjectileFromSide(img`
        . . . . 5 . 5 . 5 . 5 . 5 . . . . 
        . . . . 5 5 2 5 2 5 2 5 5 . . . . 
        . . . 1 5 2 2 2 2 2 2 2 5 1 . . . 
        . . 1 f f f f f f f f f f f 1 . . 
        . . 1 f f f f f f f f f f f 1 . . 
        . . 1 f f f f f f f f f f f 1 . . 
        . . . 1 f f f f f f f f f 1 . . . 
        . 1 1 1 f f f f f f f f f 1 1 1 . 
        1 1 1 1 f 1 f f f f f 1 f 1 1 1 1 
        1 1 . 1 f 1 f f f f f 1 f 1 . 1 1 
        1 1 . 1 f 1 1 f f f 1 1 f 1 . 1 1 
        1 1 . 1 f 1 2 1 f 1 2 1 f 1 . 1 1 
        . . . 1 f f 2 1 f 1 2 f f 1 . . . 
        . . . 1 f f f f f f f f f 1 . . . 
        . . . . 1 f f f f f f f 1 . . . . 
        . . . . . 1 1 1 1 1 1 1 . . . . . 
        `, 0, 80)
    bullet_bill.x = randint(10, 150)
    bullet_bill.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(7000, function () {
    PIGFO_RIDER = sprites.createProjectileFromSide(assets.image`P-FO RIDER`, 0, 70)
    PIGFO_RIDER.x = randint(10, 150)
    PIGFO_RIDER.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    PIGFO_RIDER.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 100)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 120)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 140)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 180)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 200)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 220)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ..............77......
        ..............77......
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 240)
    projectile = sprites.createProjectileFromSprite(img`
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......77..............
        ......77..............
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
        `, PIGFO_RIDER, 0, 260)
})
game.onUpdateInterval(2000, function () {
    flying_bombomb = sprites.createProjectileFromSide(assets.image`flying bomb-omb`, 0, 80)
    flying_bombomb.x = randint(10, 150)
    flying_bombomb.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    flying_bombomb.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(1000, function () {
    bullet_bill = sprites.createProjectileFromSide(img`
        . . . . 5 . 5 . 5 . 5 . 5 . . . . 
        . . . . 5 5 2 5 2 5 2 5 5 . . . . 
        . . . . 5 2 2 2 2 2 2 2 5 . . . . 
        . . . f f f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . . 
        . . 1 1 f f f f f f f f f 1 1 . . 
        . 1 1 1 f f f f f f f f f 1 1 1 . 
        1 1 1 1 f 1 f f f f f 1 f 1 1 1 1 
        1 1 . 1 f 1 f f f f f 1 f 1 . 1 1 
        1 1 . 1 f 1 1 f f f 1 1 f 1 . 1 1 
        1 1 . 1 f 1 2 1 f 1 2 1 f 1 . 1 1 
        . . . 1 f f 2 1 f 1 2 f f 1 . . . 
        . . . 1 f f f f f f f f f 1 . . . 
        . . . . 1 f f f f f f f 1 . . . . 
        . . . . . 1 1 1 1 1 1 1 . . . . . 
        `, 0, 80)
    bullet_bill.x = randint(10, 150)
    bullet_bill.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(1000, function () {
    flying_bombomb = sprites.createProjectileFromSide(assets.image`flying bomb-omb`, 0, 80)
    flying_bombomb.x = randint(10, 150)
    flying_bombomb.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    flying_bombomb.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(4000, function () {
    if (info.score() >= 500) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    }
})
forever(function () {
    if (info.score() >= 500) {
        sprites.destroyAllSpritesOfKind(SpriteKind.Projectile)
    } else {
    	
    }
})
game.onUpdateInterval(3500, function () {
    xwing_dark_fighter = sprites.createProjectileFromSide(img`
        . . . . 4 5 5 5 5 5 5 4 . . . . 
        . . . . . 4 5 5 5 5 4 . . . . . 
        . . . 1 1 . 4 5 5 4 . 1 1 . . . 
        2 2 2 f f 1 2 2 2 2 1 f f 2 2 2 
        . 2 1 f f f 1 1 1 1 f f f . 2 . 
        . 5 . 1 1 f f 2 2 f f 1 1 . 5 . 
        . . . . . 1 f 2 2 f 1 . . . . . 
        . 1 1 1 1 f 1 1 1 1 f 1 1 1 1 . 
        1 f f f f f 1 1 1 1 f f f f f 1 
        . 1 1 f f 1 f f f f 1 f f 1 1 . 
        . . . 2 1 1 9 9 9 9 1 1 2 . . . 
        . . . 5 . 1 f 9 9 f 1 . 5 . . . 
        . . . . . 1 f f f f 1 . . . . . 
        . . . . . . 1 f f 1 . . . . . . 
        . . . . . . 1 f f 1 . . . . . . 
        . . . . . . . 1 1 . . . . . . . 
        `, 0, 45)
    xwing_dark_fighter.x = randint(10, 150)
    xwing_dark_fighter.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    xwing_dark_fighter.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . 7 . . . . . . . . 7 . 7 . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, xwing_dark_fighter, 0, 200)
})
game.onUpdateInterval(3000, function () {
    xwing_dark_fighter = sprites.createProjectileFromSide(img`
        . . . . 4 5 5 5 5 5 5 4 . . . . 
        . . . . . 4 5 5 5 5 4 . . . . . 
        . . . 1 1 . 4 5 5 4 . 1 1 . . . 
        2 2 2 f f 1 2 2 2 2 1 f f 2 2 2 
        . 2 1 f f f 1 1 1 1 f f f . 2 . 
        . 5 . 1 1 f f 2 2 f f 1 1 . 5 . 
        . . . . . 1 f 2 2 f 1 . . . . . 
        . 1 1 1 1 f 1 1 1 1 f 1 1 1 1 . 
        1 f f f f f 1 1 1 1 f f f f f 1 
        . 1 1 f f 1 f f f f 1 f f 1 1 . 
        . . . 2 1 1 9 9 9 9 1 1 2 . . . 
        . . . 5 . 1 f 9 9 f 1 . 5 . . . 
        . . . . . 1 f f f f 1 . . . . . 
        . . . . . . 1 f f 1 . . . . . . 
        . . . . . . 1 f f 1 . . . . . . 
        . . . . . . . 1 1 . . . . . . . 
        `, 0, 45)
    xwing_dark_fighter.x = randint(10, 150)
    xwing_dark_fighter.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    xwing_dark_fighter.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . 7 . . . . . . . . 7 . 7 . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, xwing_dark_fighter, 0, 200)
})
game.onUpdateInterval(3000, function () {
    dark_beetle_bomber = sprites.createProjectileFromSide(assets.image`dark beetle bomber`, 0, 45)
    dark_beetle_bomber.x = randint(10, 150)
    dark_beetle_bomber.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
    dark_beetle_bomber.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        `, dark_beetle_bomber, 0, 250)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        `, dark_beetle_bomber, 0, 250)
})
game.onUpdateInterval(3000, function () {
    bullet_bill = sprites.createProjectileFromSide(img`
        . . . . 5 . 5 . 5 . 5 . 5 . . . . 
        . . . . 5 5 2 5 2 5 2 5 5 . . . . 
        . . . . 5 2 2 2 2 2 2 2 5 . . . . 
        . . . f f f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . . 
        . . . f f f f f f f f f f f . . . 
        . . 1 1 f f f f f f f f f 1 1 . . 
        . 1 1 1 f f f f f f f f f 1 1 1 . 
        1 1 1 1 f 1 f f f f f 1 f 1 1 1 1 
        1 1 . 1 f 1 f f f f f 1 f 1 . 1 1 
        1 1 . 1 f 1 1 f f f 1 1 f 1 . 1 1 
        1 1 . 1 f 1 2 1 f 1 2 1 f 1 . 1 1 
        . . . 1 f f 2 1 f 1 2 f f 1 . . . 
        . . . 1 f f f f f f f f f 1 . . . 
        . . . . 1 f f f f f f f 1 . . . . 
        . . . . . 1 1 1 1 1 1 1 . . . . . 
        `, 0, 80)
    bullet_bill.x = randint(10, 150)
    bullet_bill.setKind(SpriteKind.Enemy)
})
game.onUpdateInterval(3000, function () {
    projectile2 = sprites.createProjectileFromSprite(img`
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        `, dark_beetle_bomber, 0, 270)
})
game.onUpdateInterval(4500, function () {
    xwing_dark_fighter = sprites.createProjectileFromSide(img`
        . . . . 4 5 5 5 5 5 5 4 . . . . 
        . . . . . 4 5 5 5 5 4 . . . . . 
        . . . 1 1 . 4 5 5 4 . 1 1 . . . 
        2 2 2 f f 1 2 2 2 2 1 f f 2 2 2 
        . 2 1 f f f 1 1 1 1 f f f . 2 . 
        . 5 . 1 1 f f 2 2 f f 1 1 . 5 . 
        . . . . . 1 f 2 2 f 1 . . . . . 
        . 1 1 1 1 f 1 1 1 1 f 1 1 1 1 . 
        1 f f f f f 1 1 1 1 f f f f f 1 
        . 1 1 f f 1 f f f f 1 f f 1 1 . 
        . . . 2 1 1 9 9 9 9 1 1 2 . . . 
        . . . 5 . 1 f 9 9 f 1 . 5 . . . 
        . . . . . 1 f f f f 1 . . . . . 
        . . . . . . 1 f f 1 . . . . . . 
        . . . . . . 1 f f 1 . . . . . . 
        . . . . . . . 1 1 . . . . . . . 
        `, 0, 45)
    xwing_dark_fighter.x = randint(10, 150)
    xwing_dark_fighter.follow(SPACESHIP_SPACESHIP_SPACESHIP, 50)
    xwing_dark_fighter.setKind(SpriteKind.Enemy)
    xwing_dark_fighter = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . . . . . . . . . . . . 7 . 
        . 7 . 7 . . . . . . . . 7 . 7 . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . 7 . . . . . . . . 7 . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, xwing_dark_fighter, 0, 200)
})
game.onUpdateInterval(4500, function () {
    dark_beetle_bomber = sprites.createProjectileFromSide(assets.image`dark beetle bomber`, 0, 45)
    dark_beetle_bomber.x = randint(10, 150)
    dark_beetle_bomber.follow(SPACESHIP_SPACESHIP_SPACESHIP, 30)
    dark_beetle_bomber.setKind(SpriteKind.Enemy)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        `, dark_beetle_bomber, 0, 250)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        `, dark_beetle_bomber, 0, 250)
})
